version: '2'
services:
  db:
    image: mysql:5
    container_name: database
    networks:
      - customers
    environment:
      - MYSQL_ROOT_PASSWORD=supersecret
      - MYSQL_DATABASE=customers
      - MYSQL_USER=maria
      - MYSQL_PASSWORD=maria
  web:
    build: .
    container_name: webapp
    depends_on:
      - db
    ports:
      - 8080:8080
    networks:
          - customers
    environment:
      - spring.profiles.active=default
    links:
      - db
networks:
  customers:
    driver: bridge